M48
; DRILL file {KiCad 7.0.9} date Thursday, December 14, 2023 at 09:55:59 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-14T21:55:59-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0295
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T2
X0.85Y-0.91
X0.85Y-1.01
T1
G00X1.1974Y-0.82
M15
G01X1.227Y-0.82
M16
G05
G00X1.1974Y-1.0956
M15
G01X1.227Y-1.0956
M16
G05
T0
M30
